### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by HabGesehen** [laggron42/BallsDex-DiscordBot#25]
I have been making my own version of BallsDex, called MicroDex, for micronations. I have gotten setup to work before, but when I restarted, I cant start the Bot. Here is more details:

I clone the repo,
Then I create the .env
I run `docker compose build`
Then I run `docker compose up`. This should start the bot, as it has in the past, but now i get `exit code 1`. Everything in the container is started, except the bot.

Help

**Comment by HabGesehen** [comment]
Edit #1
Here is the output for the container Skipping virtualenv creation, as specified in config file.
------------------ BallsDex bot ------------------
               Collect countryballs               
          Discord bot made by El Laggron          
 Bot version:              1.3.8
 Discord.py version:       2.0.1
[2023-01-22 20:54:36] CRITICAL ballsdex: Unhandled exception.
Traceback (most recent call last):
  File "/code/ballsdex/__main__.py", line 189, in main
    loop.run_until_complete(init_tortoise(db_url))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/code/ballsdex/__main__.py", line 149, in init_tortoise
    await command.init()
  File "/usr/local/lib/python3.10/site-packages/aerich/__init__.py", line 38, in init
    await Migrate.init(self.tortoise_config, self.app, self.location)
  File "/usr/local/lib/python3.10/site-packages/aerich/migrate.py", line 69, in init
    last_version = await cls.get_last_version()
  File "/usr/local/lib/python3.10/site-packages/aerich/migrate.py", line 55, in get_last_version
    return await Aerich.filter(app=cls.app).first()
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 129, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 326, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 322, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 65, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 413, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 441, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2093, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 903, in _connect
    raise last_error
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 889, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 833, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 692, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1078, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 5432), [Errno 99] Cannot assign requested address
[2023-01-22 20:54:36] INFO tortoise: Tortoise-ORM shutdown
Skipping virtualenv creation, as specified in config file.
------------------ BallsDex bot ------------------
               Collect countryballs               
          Discord bot made by El Laggron          
 Bot version:              1.3.8
 Discord.py version:       2.0.1
[2023-01-22 21:12:47] CRITICAL ballsdex: Unhandled exception.
Traceback (most recent call last):
  File "/code/ballsdex/__main__.py", line 189, in main
    loop.run_until_complete(init_tortoise(db_url))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/code/ballsdex/__main__.py", line 149, in init_tortoise
    await command.init()
  File "/usr/local/lib/python3.10/site-packages/aerich/__init__.py", line 38, in init
    await Migrate.init(self.tortoise_config, self.app, self.location)
  File "/usr/local/lib/python3.10/site-packages/aerich/migrate.py", line 69, in init
    last_version = await cls.get_last_version()
  File "/usr/local/lib/python3.10/site-packages/aerich/migrate.py", line 55, in get_last_version
    return await Aerich.filter(app=cls.app).first()
  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 129, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 326, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 322, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 65, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 413, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 441, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2093, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 903, in _connect
    raise last_error
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 889, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 833, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/asyncpg/compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 692, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1078, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 5432), [Errno 99] Cannot assign requested address
[2023-01-22 21:12:47] INFO tortoise: Tortoise-ORM shutdown
