### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sssssssssssssssssssewwww** [laggron42/BallsDex-DiscordBot#30]
iscord.client logging in using static token
2023-02-07 17:22:48 CRITICAL ballsdex The main bot task didn't handle an exception and has crashed
Traceback (most recent call last):
  File "/home/runner/BallsDex-DiscordBot/ballsdex/__main__.py", line 136, in bot_exception_handler
    bot_task.result()
  File "/home/runner/BallsDex-DiscordBot/venv/lib/python3.10/site-packages/discord/client.py", line 745, in start
    await self.login(token)
  File "/home/runner/BallsDex-DiscordBot/venv/lib/python3.10/site-packages/discord/client.py", line 580, in login
    data = await self.http.static_login(token)
  File "/home/runner/BallsDex-DiscordBot/venv/lib/python3.10/site-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/runner/BallsDex-DiscordBot/venv/lib/python3.10/site-packages/discord/http.py", line 680, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.
2023-02-07 17:22:48 WARNING  ballsdex Attempting to die as gracefully as possible...
2023-02-07 17:22:48 INFO     ballsdex Shutting down the bot...

**Comment by laggron42** [comment]
You got ratelimited by Discord for abusing the API. I have no idea what happened, and this is not coming from Ballsdex.

Read the message given, and fix your issue with the token.
