### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by OreoMcFurry** [laggron42/BallsDex-DiscordBot#52]
the admin panel does not load. 
500
Oops… You just found an error page

We are sorry but our server encountered an internal error

this happens when I try to load the site

**Comment by OreoMcFurry** [comment]
2023-04-01 21:50:40.422 UTC [33] STATEMENT:  SELECT 1 FROM "user" LIMIT 1
ballsdex-discordbot-admin-panel-1      | INFO:     172.22.0.1:33530 - "GET /init HTTP/1.1" 500 Internal Server Error
ballsdex-discordbot-admin-panel-1      | ERROR:    Exception in ASGI application
ballsdex-discordbot-admin-panel-1      | Traceback (most recent call last):
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
ballsdex-discordbot-admin-panel-1      |     return self.receive_nowait()
ballsdex-discordbot-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
ballsdex-discordbot-admin-panel-1      |     raise WouldBlock
ballsdex-discordbot-admin-panel-1      | anyio.WouldBlock
ballsdex-discordbot-admin-panel-1      |
ballsdex-discordbot-admin-panel-1      | During handling of the above exception, another exception occurred:
ballsdex-discordbot-admin-panel-1      |
ballsdex-discordbot-admin-panel-1      | Traceback (most recent call last):
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
ballsdex-discordbot-admin-panel-1      |     message = await recv_stream.receive()
ballsdex-discordbot-admin-panel-1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 114, in receive
ballsdex-discordbot-admin-panel-1      |     raise EndOfStream
ballsdex-discordbot-admin-panel-1      | anyio.EndOfStream
ballsdex-discordbot-admin-panel-1      |
ballsdex-discordbot-admin-panel-1      | During handling of the above exception, another exception occurred:
ballsdex-discordbot-admin-panel-1      |
ballsdex-discordbot-admin-panel-1      | Traceback (most recent call last):
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
ballsdex-discordbot-admin-panel-1      |     result = await app(  # type: ignore[func-returns-value]
ballsdex-discordbot-admin-panel-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
ballsdex-discordbot-admin-panel-1      |     return await self.app(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
ballsdex-discordbot-admin-panel-1      |     await super().__call__(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.middleware_stack(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
ballsdex-discordbot-admin-panel-1      |     raise exc
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, _send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 84, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
ballsdex-discordbot-admin-panel-1      |     raise exc
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, sender)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
ballsdex-discordbot-admin-panel-1      |     raise e
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
ballsdex-discordbot-admin-panel-1      |     await route.handle(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
ballsdex-discordbot-admin-panel-1      |     await super().__call__(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.middleware_stack(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
ballsdex-discordbot-admin-panel-1      |     raise exc
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, _send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
ballsdex-discordbot-admin-panel-1      |     response = await self.dispatch_func(request, call_next)
ballsdex-discordbot-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/providers/login.py", line 135, in authenticate
ballsdex-discordbot-admin-panel-1      |     response = await call_next(request)
ballsdex-discordbot-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
ballsdex-discordbot-admin-panel-1      |     raise app_exc
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive_or_disconnect, send_no_error)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
ballsdex-discordbot-admin-panel-1      |     response = await self.dispatch_func(request, call_next)
ballsdex-discordbot-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/middlewares.py", line 19, in language_processor
ballsdex-discordbot-admin-panel-1      |     response = await call_next(request)
ballsdex-discordbot-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
ballsdex-discordbot-admin-panel-1      |     raise app_exc
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive_or_disconnect, send_no_error)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
ballsdex-discordbot-admin-panel-1      |     raise exc
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, sender)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
ballsdex-discordbot-admin-panel-1      |     raise e
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
ballsdex-discordbot-admin-panel-1      |     await route.handle(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
ballsdex-discordbot-admin-panel-1      |     await self.app(scope, receive, send)
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
ballsdex-discordbot-admin-panel-1      |     response = await func(request)
ballsdex-discordbot-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
ballsdex-discordbot-admin-panel-1      |     raw_response = await run_endpoint_function(
ballsdex-discordbot-admin-panel-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
ballsdex-discordbot-admin-panel-1      |     return await dependant.call(**values)
ballsdex-discordbot-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/providers/login.py", line 142, in init_view
ballsdex-discordbot-admin-panel-1      |     exists = await self.admin_model.all().limit(1).exists()
ballsdex-discordbot-admin-panel-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/queryset.py", line 1218, in _execute
ballsdex-discordbot-admin-panel-1      |     result, _ = await self._db.execute_query(str(self.query))
ballsdex-discordbot-admin-panel-1      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
ballsdex-discordbot-admin-panel-1      |     return await self._translate_exceptions(func, *args, **kwargs)
ballsdex-discordbot-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ballsdex-discordbot-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 84, in _translate_exceptions
ballsdex-discordbot-admin-panel-1      |     raise OperationalError(exc)
ballsdex-discordbot-admin-panel-1      | tortoise.exceptions.OperationalError: relation "user" does not exist
this is the powershell message

**Comment by OreoMcFurry** [comment]
nevermind, fixed it. in the future, everyone, make sure there are spaces before the - in the configuring of ids
